name: Deploy App

on:
  push:
    branches:
      - main  # Runs only when pushing to main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Backend Dependencies
        run: |
          cd ~/tavoai/app
          pip install -r requirements.txt

      - name: Start or Restart Backend
        run: |
          if pm2 list | grep -q "sanic-app"; then
            pm2 restart sanic-app
          else
            pm2 start ~/tavoai/app/main.py --name sanic-app --interpreter python3 -- start --host=0.0.0.0 --port=8000 --workers=4
          fi

      - name: Install Frontend Dependencies
        run: |
          cd ~/tavoai/frontend
          npm install
          npm run build
          sudo cp -r build/* /home/ubuntu/tavoai/frontend/build

      - name: Restart NGINX
        run: sudo systemctl restart nginx
